import {  
    LOGIN_START,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    login
} from './login'

import {
    GET_FRIENDS_START,
    GET_FRIENDS_SUCCESS,
    GET_FRIENDS_FAILURE,
    getFriends,

    ADD_FRIEND_START,
    ADD_FRIEND_SUCCESS,
    ADD_FRIEND_FAILURE,
    addFriend,

    REMOVE_FRIEND_START,
    REMOVE_FRIEND_SUCCESS,
    REMOVE_FRIEND_FAILURE,
    removeFriend
} from './friends'

export {
    LOGIN_START,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    login,

    GET_FRIENDS_START,
    GET_FRIENDS_SUCCESS,
    GET_FRIENDS_FAILURE,
    getFriends,

    ADD_FRIEND_START,
    ADD_FRIEND_SUCCESS,
    ADD_FRIEND_FAILURE,
    addFriend,

    REMOVE_FRIEND_START,
    REMOVE_FRIEND_SUCCESS,
    REMOVE_FRIEND_FAILURE,
    removeFriend
}